#!/bin/sh

InvalidOption=1
TooFewParms=2

#
# Temporary hack - replace with a proper message file
#
msg() {
	pgm=$1
	msgnum=$2
	msgtype=$3
	
	shift 3
	args=$*

	case ${msgnum} in 
		1) msgtext="Invalid option specified: -";;
		2) msgtext="Too few Parameters specified. Expected 2 but received: ";;
	esac
	echo "ZCL000"${msgnum}${msgtype} "${msgtext}" "${args}" >&2
}

#
# Temporary hack - replace with a manpage
#
syntax() {
	echo "\
zoscloud [-vd] search}install|uninstall|receive|configure|apply|check|uninstall <software>
	and <software> is the software to search for
	    
Examples:
	zoscloud search cobol     <-- search for products with COBOL in their description
	zoscloud install igy630   <-- install COBOL FMID IGY630 (Enterprise COBOL 6.3.0) 
	                              (install is short for receive, check, configure, apply)
	zoscloud receive igy630   <-- receive COBOL SMP/E packages from ShopZ
	zoscloud check igy630     <-- check that all pre-reqs required for COBOL 6.3.0 are satisfied
	zoscloud configure igy630 <-- configure previously checked COBOL using configuration properties
	zoscloud apply     igy630 <-- apply previously configured COBOL, making it available for general use
" >&2 
	exit 16
}

debug=0
verbose=0
while getopts ":vd" opt; do
  case ${opt} in
    d )
      debug=1
      ;;
    v )
      verbose=1
      opts="-v"
      ;;
    \?)
      if [ ${OPTARG} != "?" ]; then
	msg zoscloud ${InvalidOption} E "${OPTARG}"
      fi
      syntax
      exit 4
      ;;
  esac
done
shift $(expr $OPTIND - 1 )
if [ $# -lt 2 ]; then
	msg zoscloud ${TooFewParms} E "$#"
	syntax
	exit 16
fi
