#!/bin/sh
if [ $# != 2 ]; then
	echo "smplstzones <csi>"
	exit 4
fi
out=$(whence zbrewfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zbrewfuncs
else    	
	echo "zbrew tools need to be in your PATH" >&2
	exit 4
fi      

mydir=$(callerdir ${0})
props="${mydir}/../properties/zbrewprops.json"
zbrewpropse zbrew config "${props}"

csi="$(echo ${1} | tr '[:lower:]' '[:upper:]')"

tmpCntlHFS=${ZBREW_TMP}/$$.${tgtzone}.zonecntl.xml
zonelist=${ZBREW_TMP}/$$.${tgtzone}.zonesmp.zonelst
touch ${zonelist}

echo "  SET BOUNDARY(GLOBAL).
  LIST GZONE.
" >${tmpCntlHFS}

smpout=`smp -i ${csi} -l ${zonelist} <${tmpCntlHFS}`
rc=$?
if [ $rc -eq 0 ]; then
	tgtzones=`awk '{ if (NF==3 && $2=="TARGET") { print($1); } }' < ${zonelist}`
	rm -rf ${zonelist} ${tmpCntlHFS}
	echo "${tgtzones}"
else
	echo "${smpout}" >&2
fi
exit $rc
